### ISSUE TITLE
Create a CLI

### ISSUE THREAD

**Issue by duglin** [servicebroker/servicebroker#43]
We probably can't use the CF cli for all operations so we should just create a cli for just the user facing service related operations we're going to support.

**Comment by bmelville** [comment]
I'm going to be working on a CLI for at least the operations the service controller API supports right now.

**Comment by bmelville** [comment]
FYI @vaikas-google

**Comment by vaikas-google** [comment]
FYI, I have a simple CLI showing how it would look like with Cobra. Take a look and let me know your thoughts, it handles much of the cruft for us for free and is quite neat.

**Comment by vaikas-google** [comment]
FYI, I'm going to be adding more complete API commands this week. Just wanted to make sure nobody else was working on it also :)

**Comment by MHBauer** [comment]
@vaikas-google if you mean in the cli side, it's all yours. ping me if you want a review of something, even if it is incomplete.

**Comment by vaikas-google** [comment]
I'd like to close this because I think the CLI is there. It's not complete, but I'd rather have smaller issues tracking specific items left to do?

**Comment by bmelville** [comment]
SGTM, I'd love to see more service instance operations than create :)
